import type { Theme } from './schema'

export const PRESET_THEMES: Theme[] = [
  {
    id: 'preset-claro',
    name: 'Claro',
    background: '#ffffff',
    textColor: '#1f1f1f',
    fontFamily: 'Nunito',
    fontSize: 18,
    lineHeight: 1.6,
    margin: 48,
    isPreset: true,
  },
  {
    id: 'preset-escuro',
    name: 'Escuro',
    background: '#1a1a1f',
    textColor: '#e4e4e7',
    fontFamily: 'Nunito',
    fontSize: 18,
    lineHeight: 1.6,
    margin: 48,
    isPreset: true,
  },
  {
    id: 'preset-sepia',
    name: 'Sépia',
    background: '#f4ecd8',
    textColor: '#3b3428',
    fontFamily: 'Nunito',
    fontSize: 18,
    lineHeight: 1.6,
    margin: 48,
    isPreset: true,
  },
  {
    id: 'preset-rosa',
    name: 'Rosa Pastel',
    background: '#fdf2f6',
    textColor: '#4a2f3a',
    fontFamily: 'Quicksand',
    fontSize: 18,
    lineHeight: 1.7,
    margin: 48,
    isPreset: true,
  },
  {
    id: 'preset-lavanda',
    name: 'Lavanda',
    background: '#f5f1fb',
    textColor: '#3c3352',
    fontFamily: 'Comfortaa',
    fontSize: 18,
    lineHeight: 1.7,
    margin: 48,
    isPreset: true,
  },
  {
    id: 'preset-menta',
    name: 'Menta',
    background: '#f1faf6',
    textColor: '#254238',
    fontFamily: 'Poppins',
    fontSize: 18,
    lineHeight: 1.7,
    margin: 48,
    isPreset: true,
  },
]
